CREATE TABLE _harvest_rate
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT,
    amount     INTEGER,
    CONSTRAINT pk__harvest_rate PRIMARY KEY (id)
);

CREATE TABLE _product
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    measure VARCHAR(255),
    amount  INTEGER,
    date    date,
    CONSTRAINT pk__product PRIMARY KEY (id)
);

CREATE TABLE _record
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    product_id BIGINT,
    amount     INTEGER,
    date       date,
    CONSTRAINT pk__record PRIMARY KEY (id)
);

CREATE TABLE _user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    surname    VARCHAR(255),
    patronymic VARCHAR(255),
    password   VARCHAR(255),
    email      VARCHAR(255),
    rating     INTEGER,
    fired      BOOLEAN,
    role       VARCHAR(255),
    CONSTRAINT pk__user PRIMARY KEY (id)
);

ALTER TABLE _harvest_rate
    ADD CONSTRAINT FK__HARVEST_RATE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES _product (id);

ALTER TABLE _record
    ADD CONSTRAINT FK__RECORD_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES _product (id);

ALTER TABLE _record
    ADD CONSTRAINT FK__RECORD_ON_USER FOREIGN KEY (user_id) REFERENCES _user (id);

