services:
  db:
    image: 'postgres:15'
    container_name: database
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=1111'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:

